# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy nqpay webapp to S3

on:
  push:
    branches: ['dev', 'main']
  pull_request:
    branches: ['dev', 'main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: sa-east-1
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm install @rollup/rollup-linux-x64-gnu
      - run: npm run build --if-present
      - run: npm run domain
      - name: Deploy to AWS S3 (Dev)
        if: github.ref == 'refs/heads/dev'
        run: |
          aws s3 sync dist s3://paydev.nqpay.lat --delete
      - name: Deploy to AWS S3 (Main)
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 sync dist s3://payprod.nqpay.lat --delete
